### ISSUE TITLE
Invalid config field backend model: amazonpayments/system_config_backend_dataPolling_cron

### ISSUE THREAD

**Issue by ghost** [kirchbergerknorr/Creativestyle_AmazonPayments#3]
Hello,

first of all thanks for extension. I have a question.
I've installed this extension on my local and it works fine. But when I tried to install it on live I got an exception like "Invalid config field backend model: amazonpayments/system_config_backend_dataPolling_cron". I cannot open Magento System Configuration page. Could you help me, what I'm doing wrong?

**Comment by Lmbrtz** [comment]
Hi devstdo,

unfortunately, we cannot provide any support for this repo. Please contact the module developers for support. You can find the module here: https://www.magentocommerce.com/magento-connect/pay-with-amazon-for-magento-1.html.

Thank you!
